local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

cloudinary:
  service: Cloudinary
  # resource_type: 'raw'
  upload:
    use_filename: true
    unique_filename: false
